
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS imp_uid VARCHAR(100) DEFAULT NULL;

ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS merchant_uid VARCHAR(100) DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_imp_uid ON orders(imp_uid);
CREATE INDEX IF NOT EXISTS idx_merchant_uid ON orders(merchant_uid);
